# backend/app/models/cognitive_fingerprint.py
"""Cognitive fingerprint model for kg_driven simulation agents."""
from __future__ import annotations
from dataclasses import dataclass


@dataclass(frozen=True)
class CognitiveFingerprint:
    """Immutable cognitive profile for simulation agents.

    Generated by KGAgentFactory during agent creation.
    Governs belief update dynamics, information consumption, and social influence.
    """

    agent_id: str

    # Moral/political values — variable-length, LLM-inferred from seed text.
    # Keys are scenario-specific (e.g. "authority", "loyalty", "fairness").
    # 3–12 keys required; all values must be in [0.0, 1.0].
    values: dict[str, float]

    # Information source tags this agent consumes.
    # Must match WorldEvent.reach tags; non-empty.
    info_diet: tuple[str, ...]

    # Social group memberships (multi-membership allowed).
    group_memberships: tuple[str, ...]

    # Sensitivity per shock category; keys match UniversalShockType.id values.
    susceptibility: dict[str, float]

    # 0 = fully open to new evidence; 1 = fully closed. Clamped to [0, 1].
    confirmation_bias: float

    # 0 = fully independent; 1 = fully follows crowd. Clamped to [0, 1].
    conformity: float

    def __post_init__(self) -> None:
        if not (3 <= len(self.values) <= 12):
            raise ValueError(
                f"values must have 3–12 keys, got {len(self.values)}"
            )
        for k, v in self.values.items():
            if not (0.0 <= v <= 1.0):
                raise ValueError(
                    f"values must be in [0, 1]; key '{k}' has value {v}"
                )
        if not self.info_diet:
            raise ValueError("info_diet must not be empty")
        if not (0.0 <= self.confirmation_bias <= 1.0):
            raise ValueError(
                f"confirmation_bias must be in [0, 1], got {self.confirmation_bias}"
            )
        if not (0.0 <= self.conformity <= 1.0):
            raise ValueError(
                f"conformity must be in [0, 1], got {self.conformity}"
            )
