"""Per-session kg_driven state container.

Wraps the 12 per-session dicts/lists that were previously scattered across
SimulationRunner.__init__ into a single mutable dataclass.  One instance is
created per session when kg_driven mode activates and destroyed on cleanup.

Deliberately NOT frozen — fields are updated in-place during simulation rounds
by SimulationRunner hook methods.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class KGSessionState:
    """Mutable per-session state for kg_driven simulation mode.

    All collection fields default to empty via field(default_factory=...) so
    that constructing a fresh instance requires no arguments.

    Fields mirror the former per-session dicts in SimulationRunner keyed by
    session_id — the outer session_id key is no longer needed because this
    object IS the session-scoped container.
    """

    # Pre-round world events generated by WorldEventGenerator
    current_round_events: list = field(default_factory=list)

    # Running history of event content strings (deduplication + context window)
    event_content_history: list[str] = field(default_factory=list)

    # Stakeholder agent dicts (id, name, role, faction) loaded from DB
    stakeholder_agents: list = field(default_factory=list)

    # metric_id → current float value (0..1) for active scenario metrics
    active_metrics: dict[str, float] = field(default_factory=dict)

    # agent_id → {metric_id → belief float} for all tracked agents
    agent_beliefs: dict[str, dict[str, float]] = field(default_factory=dict)

    # Per-round snapshots of agent_beliefs (appended each round)
    belief_history: list = field(default_factory=list)

    # Adjacency list: agent_id → list[agent_id] of interacted agents
    interaction_graph: dict[str, list[str]] = field(default_factory=dict)

    # metric_id → dominant stance float from previous round (tipping detection)
    prev_dominant_stance: dict[str, float] = field(default_factory=dict)

    # Seed text excerpt used as scenario description for LLM prompts
    scenario_description: str = ""

    # (agent_a_id, agent_b_id) → RelationshipState (multi-dim)
    relationship_states: dict[tuple[str, str], Any] = field(default_factory=dict)

    # agent_id → AttachmentStyle (derived from Big Five at session start)
    attachment_styles: dict[str, Any] = field(default_factory=dict)

    # agent_id → EmotionalState (updated per-round by EmotionalEngine)
    emotional_states: dict[str, Any] = field(default_factory=dict)

    # agent_id → faction_id (updated every 3 rounds by FactionMapper; empty until first compute)
    agent_factions: dict[str, str] = field(default_factory=dict)

    # agent_id → {"plan": str, "horizon": int, "created_round": int}
    # Multi-round strategic plans for stakeholder agents (Phase 4)
    agent_strategies: dict[str, dict] = field(default_factory=dict)

    # Auto-fork guards: count of forks created + rounds already forked
    auto_fork_count: int = 0
    auto_fork_rounds: list[int] = field(default_factory=list)

    # All agent dicts (id, name, role, faction, is_stakeholder, activity_level)
    # loaded from DB — used by stochastic activation each round
    all_agent_dicts: list[dict[str, Any]] = field(default_factory=list)

    # Optional deterministic seed for stochastic activation RNG
    activation_seed: int | None = None

    # Lite ensemble mode: use rule-based hooks instead of LLM
    lite_ensemble: bool = False

    # Per-agent previous-round decision for strategic momentum in lite mode
    agent_prev_decisions: dict[str, str] = field(default_factory=dict)

    # LLM failure tracking for auto-degradation to lite mode (Phase 1.1)
    # Counts consecutive rounds where ≥80% of LLM calls failed
    consecutive_llm_failures: int = 0
    # True once auto-degradation has been triggered (reset only on LLM recovery)
    auto_degraded_to_lite: bool = False
