"""Per-session kg_driven state container.

Wraps the 12 per-session dicts/lists that were previously scattered across
SimulationRunner.__init__ into a single mutable dataclass.  One instance is
created per session when kg_driven mode activates and destroyed on cleanup.

Deliberately NOT frozen — fields are updated in-place during simulation rounds
by SimulationRunner hook methods.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass
class KGSessionState:
    """Mutable per-session state for kg_driven simulation mode.

    All collection fields default to empty via field(default_factory=...) so
    that constructing a fresh instance requires no arguments.

    Fields mirror the former per-session dicts in SimulationRunner keyed by
    session_id — the outer session_id key is no longer needed because this
    object IS the session-scoped container.
    """

    # Pre-round world events generated by WorldEventGenerator
    current_round_events: list = field(default_factory=list)

    # Running history of event content strings (deduplication + context window)
    event_content_history: list[str] = field(default_factory=list)

    # Top-N Tier 1 agent dicts (id, name, role, faction) loaded from DB
    tier1_agents: list = field(default_factory=list)

    # metric_id → current float value (0..1) for active scenario metrics
    active_metrics: dict[str, float] = field(default_factory=dict)

    # agent_id → {metric_id → belief float} for all tracked agents
    agent_beliefs: dict[str, dict[str, float]] = field(default_factory=dict)

    # Per-round snapshots of agent_beliefs (appended each round)
    belief_history: list = field(default_factory=list)

    # Adjacency list: agent_id → list[agent_id] of interacted agents
    interaction_graph: dict[str, list[str]] = field(default_factory=dict)

    # metric_id → dominant stance float from previous round (tipping detection)
    prev_dominant_stance: dict[str, float] = field(default_factory=dict)

    # Seed text excerpt used as scenario description for LLM prompts
    scenario_description: str = ""

    # (agent_a_id, agent_b_id) → RelationshipState (multi-dim)
    relationship_states: dict[tuple[str, str], Any] = field(default_factory=dict)

    # agent_id → AttachmentStyle (derived from Big Five at session start)
    attachment_styles: dict[str, Any] = field(default_factory=dict)

    # agent_id → EmotionalState (updated per-round by EmotionalEngine)
    emotional_states: dict[str, Any] = field(default_factory=dict)
